name: Build Frontend

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'frontend/**'
      - '.github/workflows/build-frontend.yml'
  workflow_dispatch:

# Пропускаем запуск, если коммит сделан GitHub Actions (избегаем бесконечного цикла)
concurrency:
  group: build-frontend
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Build frontend
        run: |
          cd frontend
          npm run build
          
      - name: Commit built files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Синхронизируемся с удаленной веткой перед коммитом
          git fetch origin main
          git rebase origin/main || git reset --hard origin/main
          # Принудительно добавляем файлы, даже если они игнорируются
          git add -f app/static/
          # Проверяем статус и коммитим только если есть изменения
          if ! git diff --staged --quiet; then
            git commit -m "chore: rebuild frontend [skip ci]"
            # Используем rebase вместо merge для избежания конфликтов
            git pull --rebase origin main || true
            git push origin main
          else
            echo "No changes to commit"
          fi

